#!/usr/bin/env bash
set -euo pipefail

# Enable CachyOS kernel COPR
dnf copr enable -y bieszczaders/kernel-cachyos

# Install kernel-cachyos replacing stock Fedora kernel.
# --setopt=tsflags=noscripts skips %posttrans scriptlets, which prevents
# the rpm-ostree kernel install hook from calling dracut before modules.dep
# exists. depmod runs below; initramfs is regenerated by the bluebuild
# initramfs module at the end of the recipe.
dnf install -y \
    --allowerasing \
    --setopt=tsflags=noscripts \
    kernel-cachyos

# Remove any remaining stock kernel packages not cleaned up by --allowerasing
rpm -e --nodeps \
    kernel kernel-core kernel-modules kernel-modules-core kernel-modules-extra \
    2>/dev/null || true

# Generate modules.dep so dracut can build the initramfs
KVER=$(ls /usr/lib/modules/ | grep -i cachyos | head -1)
if [ -z "$KVER" ]; then
    echo "ERROR: CachyOS kernel not found in /usr/lib/modules/" >&2
    exit 1
fi
echo "Running depmod for $KVER"
depmod -a "$KVER"
